nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: Find your phone!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT     
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc)(?!_error)